---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
spec:
  ports:
    - port: {{ .Values.grafana.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.grafana.portName }}
  selector:
    app: {{ .Values.grafana.name }}
