---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.teslamate.name }}
spec:
  ports:
    - port: {{ .Values.teslamate.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.teslamate.portName }}
  selector:
    app: {{ .Values.teslamate.name }}
